spring:
  datasource:
    url: jdbc:mysql://localhost:3306/new_schema2 #Нужно указать вашу БД
    username: root # пользователь который указат у вас при создании БД
    password: password # пароль который указат у вас при создании БД
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  thymeleaf:
    cache: false

server:
  port: 8081
